import { Spacer, Text } from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { OgpCard } from '../components/domains/Ogp/OgpCard';
import { usePages } from '../hooks/Page';

const Home: NextPage = () => {
  const { data: pages } = usePages();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ maxWidth: '500px', margin: '0 auto', padding: '0px 16px' }}>
        <Spacer y={1} />
        <Text h2>Welcome to Wiscro !</Text>
        <Spacer y={1} />
        <div style={{ rowGap: '16px', display: 'flex', flexDirection: 'column' }}>
          {pages?.map((page) => (
            <OgpCard key={page._id} page={page} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
